# Generated by Django 4.0.6 on 2022-08-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_place_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellingplaces',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
