# Generated by Django 4.0.6 on 2022-08-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_place_api', '0002_alter_travellingplaces_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellingplaces',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
