# Generated by Django 4.0.6 on 2022-08-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelling_place_api', '0003_alter_travellingplaces_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travellingplaces',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='travellingplaces',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='travellingplaces',
            name='place_name',
            field=models.CharField(max_length=200),
        ),
    ]
